version: "3.9"
services:
  db: #other name doesn't work
    container_name: db_adex
    image: mysql:latest
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: mysql #username: root, pass: mysql
        MYSQL_USER: nam
        MYSQL_PASSWORD: 123456
        MYSQL_DATABASE: customer_DB
    ports:
        - 3306:3306
    #cap_add:
    #  - SYS_NICE  # CAP_SYS_NICE
    command: --init-file /var/www/html/MySQL/init.sql
    volumes:
        - .\MySQL:/var/www/html/MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_adex
    restart: always
    ports:
      - 1357:80
    environment:
      - PMA_ARBITRARY=1

